// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TacBlog.Acceptance.Tests.Features.Epic4_PublicReading
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "epic4")]
    [Xunit.TraitAttribute("Category", "api")]
    public partial class SeeRelatedPostsFeature : object, Xunit.IClassFixture<SeeRelatedPostsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic4",
                "api"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features/Epic4_PublicReading", "See related posts", "  As a reader\n  I want to see related posts at the bottom of an article\n  So that" +
                " I can continue reading about similar topics", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RelatedPosts.feature"
#line hidden
        
        public SeeRelatedPostsFeature(SeeRelatedPostsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Related posts shown based on shared tags")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Related posts shown based on shared tags")]
        public async global::System.Threading.Tasks.Task RelatedPostsShownBasedOnSharedTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts shown based on shared tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "title",
                            "tags"});
                table22.AddRow(new string[] {
                            "TDD Is Not About Testing",
                            "TDD, Clean Code"});
                table22.AddRow(new string[] {
                            "The Red-Green-Refactor Cycle",
                            "TDD"});
                table22.AddRow(new string[] {
                            "Test Doubles Explained",
                            "TDD, Testing"});
                table22.AddRow(new string[] {
                            "Why Value Objects Matter",
                            "DDD"});
#line 13
    await testRunner.GivenAsync("these published posts exist:", ((string)(null)), table22, "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync("a reader requests related posts for \"tdd-is-not-about-testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "The Red-Green-Refactor Cycle"});
                table23.AddRow(new string[] {
                            "Test Doubles Explained"});
#line 20
    await testRunner.ThenAsync("the related posts include:", ((string)(null)), table23, "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("\"Why Value Objects Matter\" is not in the related posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("\"TDD Is Not About Testing\" is not in the related posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Related posts ranked by shared tag count then date")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Related posts ranked by shared tag count then date")]
        public async global::System.Threading.Tasks.Task RelatedPostsRankedBySharedTagCountThenDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts ranked by shared tag count then date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "title",
                            "date",
                            "tags"});
                table24.AddRow(new string[] {
                            "TDD Is Not About Testing",
                            "2026-03-05",
                            "TDD, Clean Code, SOLID"});
                table24.AddRow(new string[] {
                            "Clean Code Fundamentals",
                            "2026-03-04",
                            "Clean Code, SOLID"});
                table24.AddRow(new string[] {
                            "Red-Green-Refactor",
                            "2026-03-03",
                            "TDD"});
                table24.AddRow(new string[] {
                            "SOLID Deep Dive",
                            "2026-03-02",
                            "SOLID"});
#line 27
    await testRunner.GivenAsync("these published posts exist:", ((string)(null)), table24, "Given ");
#line hidden
#line 33
    await testRunner.WhenAsync("a reader requests related posts for \"tdd-is-not-about-testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the first related post is \"Clean Code Fundamentals\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("\"Clean Code Fundamentals\" appears before \"Red-Green-Refactor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("\"Red-Green-Refactor\" appears before \"SOLID Deep Dive\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Related posts tie-break by newest date")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Related posts tie-break by newest date")]
        public async global::System.Threading.Tasks.Task RelatedPostsTie_BreakByNewestDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts tie-break by newest date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "title",
                            "date",
                            "tags"});
                table25.AddRow(new string[] {
                            "TDD Is Not About Testing",
                            "2026-03-05",
                            "TDD"});
                table25.AddRow(new string[] {
                            "Older TDD Post",
                            "2026-03-01",
                            "TDD"});
                table25.AddRow(new string[] {
                            "Newer TDD Post",
                            "2026-03-04",
                            "TDD"});
#line 39
    await testRunner.GivenAsync("these published posts exist:", ((string)(null)), table25, "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("a reader requests related posts for \"tdd-is-not-about-testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("\"Newer TDD Post\" appears before \"Older TDD Post\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Related posts limited to 3")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Related posts limited to 3")]
        public async global::System.Threading.Tasks.Task RelatedPostsLimitedTo3()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts limited to 3", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "title",
                            "tags"});
                table26.AddRow(new string[] {
                            "TDD Is Not About Testing",
                            "TDD"});
                table26.AddRow(new string[] {
                            "Related Post 1",
                            "TDD"});
                table26.AddRow(new string[] {
                            "Related Post 2",
                            "TDD"});
                table26.AddRow(new string[] {
                            "Related Post 3",
                            "TDD"});
                table26.AddRow(new string[] {
                            "Related Post 4",
                            "TDD"});
#line 48
    await testRunner.GivenAsync("these published posts exist:", ((string)(null)), table26, "Given ");
#line hidden
#line 55
    await testRunner.WhenAsync("a reader requests related posts for \"tdd-is-not-about-testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.ThenAsync("exactly 3 related posts are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Current post is excluded from related posts")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Current post is excluded from related posts")]
        public async global::System.Threading.Tasks.Task CurrentPostIsExcludedFromRelatedPosts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Current post is excluded from related posts", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "title",
                            "tags"});
                table27.AddRow(new string[] {
                            "TDD Is Not About Testing",
                            "TDD"});
                table27.AddRow(new string[] {
                            "Another TDD Post",
                            "TDD"});
#line 59
    await testRunner.GivenAsync("these published posts exist:", ((string)(null)), table27, "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("a reader requests related posts for \"tdd-is-not-about-testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("\"TDD Is Not About Testing\" is not in the related posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No related posts available")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "No related posts available")]
        public async global::System.Threading.Tasks.Task NoRelatedPostsAvailable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No related posts available", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
    await testRunner.GivenAsync("only one post exists tagged \"Architecture\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
    await testRunner.WhenAsync("a reader requests related posts for that post", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("the related posts list is empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Related posts for a non-existent post")]
        [Xunit.TraitAttribute("FeatureTitle", "See related posts")]
        [Xunit.TraitAttribute("Description", "Related posts for a non-existent post")]
        public async global::System.Threading.Tasks.Task RelatedPostsForANon_ExistentPost()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts for a non-existent post", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
    await testRunner.WhenAsync("a reader requests related posts for \"nonexistent-slug\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("the response status is 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SeeRelatedPostsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SeeRelatedPostsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
